config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }
  get 'messages/new'
  root to: "posts#index"
  resources :posts do
    resources :comments, only: :create
    resources :likes, only: [:create, :destroy]
  end
  resources :messages, only: [:new, :create]
  resources :users, only: [:show] do
    collection do
      get :likes
    end
  end
  
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user

  validates_uniqueness_of :post_id, scope: :user_id
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_post, only: [:create, :destroy]

  def create
    @like = Like.create(user_id: current_user.id, post_id: params[:post_id])
  end

  def destroy
    like = Like.find_by(user_id: current_user.id, post_id: params[:post_id])
    like.destroy
  end

  private

  def set_post
    @post = Post.find(params[:post_id])
  end
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/likes/_like.html.erb
<% if user_signed_in? %>

  <% unless @post.like_user(current_user.id).blank? %>
    <%= link_to post_like_path(post_id: @post.id, id: @post.likes[0].id), method: :delete, remote: true do %>
      <div class="vertical_like">
       <%= image_tag "icon_red_heart.png", size: '40x40' %>
      </div>
    <% end %>
  <% else %>
    <%= link_to post_likes_path(@post.id), method: :post, remote: true do %>
      <div class="vertical_like">
        <%= image_tag "icon_heart.png", size: '40x40' %>
      </div>
    <% end %>
  <% end %>
<% end %>

app/views/likes/create.js.erb
$('#likes_buttons<%= @post.id %>').html("<%= j(render partial: 'likes/like', locals: {post: @post,like: @like}) %>");

app/views/likes/destroy.js.erb
$('#likes_buttons<%= @post.id %>').html("<%= j(render partial: 'likes/like', locals: {post: @post, like: @like}) %>");